services:
  - type: web
    name: dga
    env: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn --worker-class gevent bsapps.wsgi:application"
    plan: free
    branch: main
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: dga_db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4